### ISSUE TITLE
Doesn't find any files on Windows

### ISSUE THREAD

**Issue by DanTup** [ksmolyanin/run-for-every-file#5]
This works fine on Linux, but reports `No one file has been found! Command didn't run.` on Windows.

I've tried both of these in my package.json:

```text
"remap_empty_coverage": "cd out/src && run-for-every-file --src '../../.nyc_output/*.json' --run \"remap-istanbul -i '{{src-file}}' -o '{{src-file}}'\" && cd ../..",
"remap_empty_coverage": "cd out/src && run-for-every-file --src '../../.nyc_output/' --file '**/*.json' --run \"remap-istanbul -i '{{src-file}}' -o '{{src-file}}'\" && cd ../..",
```

Both report the same. First one works fine on Mac/Linux (haven't tried second one).

There is a single json file at `myproject\.nyc_output`. I have to run remap-istantbul from inside `out\src` to make paths line up (!). Happens same both on my local Windows machine and AppVeyor:

https://ci.appveyor.com/project/DanTup/dart-code/build/0.0.1450

```text
> cd out/src && run-for-every-file --src '../../.nyc_output/*.json' --run "remap-istanbul -i '{{src-file}}' -o '{{src-file}}'" && cd ../..
No one file has been found! Command didn't run.
```

Whereas on Travis it works fine:

https://travis-ci.org/Dart-Code/Dart-Code/jobs/355966720

```text
> dart-code@2.11.0-dev remap_empty_coverage /home/travis/build/Dart-Code/Dart-Code
> cd out/src && run-for-every-file --src '../../.nyc_output/*.json' --run "remap-istanbul -i '{{src-file}}' -o '{{src-file}}'" && cd ../..
COMMAND: remap-istanbul -i '../../.nyc_output/a88bcb40205f7cafd9ab6803630c4cbd.json' -o '../../.nyc_output/a88bcb40205f7cafd9ab6803630c4cbd.json'
```

I have confirmed the json file is being output. I'll try and do some more digging when I get time.

**Comment by DanTup** [comment]
😢 Ofc it works when run manually :/

```
PS M:\Coding\Applications\Dart-Code\out\src> ..\..\node_modules\.bin\run-for-every-file --src '../../.nyc_output/*.json' --run "echo {{src-file}}"
COMMAND: echo ../../.nyc_output/1c988809a93314ca53ff422d26dd2524.json
../../.nyc_output/1c988809a93314ca53ff422d26dd2524.json
```

**Comment by DanTup** [comment]
Works from PoSh but not CMD :/

![run-for-every-file](https://user-images.githubusercontent.com/1078012/37674099-eef7574c-2c69-11e8-8a02-76904601f2f9.png)

**Comment by DanTup** [comment]
Cannot get any files to ever match in `CMD.exe` regardless of inputs:

![cmd2](https://user-images.githubusercontent.com/1078012/37674271-5b74a244-2c6a-11e8-84d2-f2162114b5d4.png)

**Comment by DanTup** [comment]
Ugh, changing to double quotes (and removing the quotes around {{src-file}} fixed it. Not really sure why :/

Fixed for me, but leaving this open in case you wish to investigate.

**Comment by ksmolyanin** [comment]
Single quotas work in Linux and MacOS but not Windows. As far as I know everybody should use only double quotas in Windows command line.
